---
name: rubocop-ast
version: '1.46'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 27ffa6e96f601d8c9917e62cadf72e64731620a5
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
