class TodosController < ApplicationController
  @form: untyped

  # [GET]...
  def index: () -> Todo

  # [GET]...
  def show: () -> untyped

  # [GET]...
  def new: () -> untyped

  # [POST]...
  def create: () -> untyped

  # [GET]...
  def edit: () -> untyped

  # [PUT]...
  def update: () -> untyped

  # [DELETE]...
  def destroy: () -> untyped
end
