module ::Todos
end

class ApplicationForm
  extend ActiveModel::Translation

  include ActiveModel::Model

  include ActiveModel::Attributes

  include ActiveModel::Validations::Callbacks

  extend Enumerize

  # Class-level DSL methods
  def self.attribute: (*untyped) -> untyped
  def self.validates: (*untyped) -> untyped
  def self.enumerize: (*untyped) -> untyped

  def initialize: (?::Hash[untyped, untyped] attributes) -> void

  def valid!: () -> (untyped | nil)

  private

  def error_messages: () -> untyped

  def attribute_names: () -> ::Array[untyped]
end
